package po;

// Generated 2016-8-1 16:45:00 by Hibernate Tools 3.4.0.CR1

/**
 * XinhuaNews generated by hbm2java
 */
public class XinhuaNews implements java.io.Serializable {

	private Long id;
	private String webName;
	private String navigation;
	private String classify;
	private String classifyDetail;
	private String url;
	private String webLevel;
	private String ranking;
	private String belonging;

	public XinhuaNews() {
	}

	public XinhuaNews(Long id) {
		this.id = id;
	}

	public XinhuaNews(Long id, String webName, String navigation,
			String classify, String classifyDetail, String url,
			String webLevel, String ranking, String belonging) {
		this.id = id;
		this.webName = webName;
		this.navigation = navigation;
		this.classify = classify;
		this.classifyDetail = classifyDetail;
		this.url = url;
		this.webLevel = webLevel;
		this.ranking = ranking;
		this.belonging = belonging;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getWebName() {
		return this.webName;
	}

	public void setWebName(String webName) {
		this.webName = webName;
	}

	public String getNavigation() {
		return this.navigation;
	}

	public void setNavigation(String navigation) {
		this.navigation = navigation;
	}

	public String getClassify() {
		return this.classify;
	}

	public void setClassify(String classify) {
		this.classify = classify;
	}

	public String getClassifyDetail() {
		return this.classifyDetail;
	}

	public void setClassifyDetail(String classifyDetail) {
		this.classifyDetail = classifyDetail;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getWebLevel() {
		return this.webLevel;
	}

	public void setWebLevel(String webLevel) {
		this.webLevel = webLevel;
	}

	public String getRanking() {
		return this.ranking;
	}

	public void setRanking(String ranking) {
		this.ranking = ranking;
	}

	public String getBelonging() {
		return this.belonging;
	}

	public void setBelonging(String belonging) {
		this.belonging = belonging;
	}

}
